rmdir /s /q MABMoney.Caching\bin
rmdir /s /q MABMoney.Caching\obj
rmdir /s /q MABMoney.Data\bin
rmdir /s /q MABMoney.Data\obj
rmdir /s /q MABMoney.Domain\bin
rmdir /s /q MABMoney.Domain\obj
rmdir /s /q MABMoney.Services\bin
rmdir /s /q MABMoney.Services\obj
rmdir /s /q MABMoney.Tests\bin
rmdir /s /q MABMoney.Tests\obj
rmdir /s /q MABMoney.Web\bin
rmdir /s /q MABMoney.Web\obj